### ISSUE TITLE
keeps ringing 

### ISSUE THREAD

**Issue by Andy1996247** [twilio-labs/call-gpt#13]
setting up Call-gpt went great. but when i call my twilio number i keeps ringing ,no answer then hangs up. On ngrok im getting 200 OK. i did run npm test everything was great. Am i missing something or what could be the problem?

**Comment by Andy1996247** [comment]
i fixed the issue. i didn't add the ngrok url probably to .evn file.

**Comment by cweems** [comment]
Great to hear you've solved it! Yes, without the ngrok URL Twilio won't know where to send the media stream data.
