### ISSUE TITLE
Forward call

### ISSUE THREAD

**Issue by Andy1996247** [twilio-labs/call-gpt#15]
How would one create a function to forward the call to another number? Let's say gpt hears some emergency keywords  (like "I'm hurt" or something like that). How would i forward the using twilio webhook or restapi via the twilio Studio or another way.

**Comment by cweems** [comment]
Hi @Andy1996247, I've added an example of how to do this here: https://github.com/twilio-labs/call-gpt/blob/main/functions/transferCall.js

The function-manifest definition is here: https://github.com/twilio-labs/call-gpt/blob/main/functions/transferCall.js
