### ISSUE TITLE
I get this issue

### ISSUE THREAD

**Issue by ChamathRosh** [twilio-labs/call-gpt#17]
when i run "npm run outbound" i get this issue
![image_2024-03-10_093319126](https://github.com/twilio-labs/call-gpt/assets/141238150/81f23440-f1f5-49ac-b8b8-e00f185bfa8c)

**Comment by ChamathRosh** [comment]
Thank You so much now i see that typing error in env file
and can i know how to handle inbound calls with this

**Comment by ansario** [comment]
@chamanthrosh it should be the same process, are you running into an error?

**Comment by ChamathRosh** [comment]
how can i change this one "Hello! I understand you're looking for a pair of AirPods, is that correct?" that comes when we first pickup the phone. I tried to change that in gpt-service but it didn't change always say the above one when I pickup the phone

**Comment by ansario** [comment]
If you changed the system prompts in gpt-service, you'll also need to update the incoming voice from Twilio here: https://github.com/twilio-labs/call-gpt/blob/78e88db5a3036ecbeef9c0f53982af77e0083a5a/scripts/inbound-call.js#L15.

**Comment by ChamathRosh** [comment]
I still get this "Hello! I understand you're looking for a pair of AirPods, is that correct?" as the first thing when i answer the call these are the changes that i have done can you help to find out how can i change that one
![ai call2](https://github.com/twilio-labs/call-gpt/assets/141238150/876a8202-fd56-4b6b-a156-dff0e1eb8896)
![AI CALL](https://github.com/twilio-labs/call-gpt/assets/141238150/07da8b5d-03c6-4771-849e-4bdaec2308fb)
![aicall3](https://github.com/twilio-labs/call-gpt/assets/141238150/547570b0-c588-4d43-ac0a-7f8ae7fa110f)

**Comment by ansario** [comment]
Are you sure you've deployed / saved your code properly?

**Comment by cweems** [comment]
@ChamathRosh I believe this is the line you are looking to change: https://github.com/twilio-labs/call-gpt/blob/main/app.js#L51

You can also update this line to give the bot context about what intro message was said: https://github.com/twilio-labs/call-gpt/blob/main/services/gpt-service.js#L20
