### ISSUE TITLE
Getting click sounds and static sounds on the phone when run.

### ISSUE THREAD

**Issue by cyai** [twilio-labs/call-gpt#18]
I am getting just click sounds and static sounds the one you get when you tap the mic and then nothing.

Any reason why this is happening?

**Comment by Sheldenshi** [comment]
I am getting this too

**Comment by ninjas005** [comment]
I am also getting shot noises instead of speech in my phone. What could be the problem causing this?

**Comment by ninjas005** [comment]
anyone find a solution for this

**Comment by cyai** [comment]
I figured it out. For me it was the issue with the TTS service I was using, ElevenLabs. I ran out of credits there so it was throwing me the error. I wasn't handling the error properly in my code thus the error was being streamed which was leading to the clicking sound. 

Check if the audio you are trying to stream is actually an audio buffer, it might be something else which might lead to the clicking sound

**Comment by ninjas005** [comment]
Thankyou, will check the status of my eleven labs subscription

**Comment by cweems** [comment]
This should be resolved now that the default TTS provider is deepgram. I've had fewer issues with them rate-limiting me. I also added a check in the Eleven Labs example to log an error if there's non 200 error code.
