### ISSUE TITLE
Explicitly order outgoing audio chunks to avoid race condition

### ISSUE THREAD

**Issue by cweems** [twilio-labs/call-gpt#2]
We send chunks of text to ElevenLabs that are different lengths. Generally speaking, the STT recordings come back in the right order. But in some circumstances a very short recording might be processed faster than a longer one and arrive first, even though it was meant to be played later.

We should create a cache for ElevenLabs recordings and re-order outgoing recordings to Twilio Media Streams as necessary so that they follow the correct sequence.

**Comment by mbui41** [comment]
Hi Cweems. Is there a way to contact you?
