### ISSUE TITLE
Please create another option for  speech to text using Deepgram Aurora

### ISSUE THREAD

**Issue by gauravkesharwani** [twilio-labs/call-gpt#24]
Could you please create another option for  speech to text using Deepgram Aurora? It has lower latency that ElevenLabs, improving the overall experience.

**Comment by cweems** [comment]
Thanks @gauravkesharwani, it looks like Deepgram Aura is still waitlist access, but I've signed up for the waitlist.

**Comment by cweems** [comment]
Hi @gauravkesharwani, just wanted to follow up to say that I've integrated Deepgram Aura and it's now the default speech provider. Thanks for the suggestion.

**Comment by gauravkesharwani** [comment]
Thank you so much for this! Latency has been significantly reduced.
