### ISSUE TITLE
how i can run this code and voice call to gpt 

### ISSUE THREAD

**Issue by muhammadadildeveloper999** [twilio-labs/call-gpt#28]
anyone can quickly tell me how i can run this code that i can conversation to gpt on my phone number
i also follow the steps of readme.MD i have run the server of using (npm run dev
) this command then i run this command (twilio phone-numbers:update +1[your-twilio-number] --voice-url=https://your-server.ngrok.io/incoming
) and then i make call of my number to twilio number but after one 1-2 second call has drop and chatgpt
donot connect with me ?? any one that can tell how i can run the code and how i talk to gpt

**Comment by dolgoonnn** [comment]
hey how did fix the issue? I just ran into same one

**Comment by MuhammadAdil-Developer** [comment]
In the .env i use the ngrok url without https:// so this problem has been solved
