### ISSUE TITLE
Wrong inputs in function call

### ISSUE THREAD

**Issue by jakepgoldman** [twilio-labs/call-gpt#30]
https://github.com/twilio-labs/call-gpt/blob/9968aded01823d23940f57c10b05b1aed779b780/services/gpt-service.js#L111

The function `updateUserContext(name, role, text)` has the following order of params, but in the function call when using tools within the gpt-service, you have the ordering as ` this.updateUserContext('function', functionName, functionResponse);` which is `(role, name, text)`. This causes all of the tool fns to throw since it's expecting a role type of `function` but you are passing in the function name instead.

**Comment by mercuryyy** [comment]
Fix is here - https://github.com/twilio-labs/call-gpt/pull/32

you can copy code or just fork and pull
