### ISSUE TITLE
Deepgram for TTS

### ISSUE THREAD

**Issue by mercuryyy** [twilio-labs/call-gpt#33]
I got Deepgram to somewhat work for TTS but it only supports "mulaw" which works with twilio but there is an odd click/noise each time a new audio file starts playback. 

Anyone been able to get it to work smoothly? maybe encoding the chunks and then sending to base64 ?

Deegram these days is a much better choices then 11lab, cheaper and faster for TTS.

**Comment by Vri6500** [comment]
i am having odd click/noise with 11labs TTS, were you able to fix that one? I have still not exhausted the character limit of 11labs. I can hear partial audio. Not sure how to fix it. With neets ai, i am not having this issue. Thank you

**Comment by SageWorks4925** [comment]
Try giving _container=none_ when setting the audio format. Please refer the deepgram FAQ screenshot and link.

Link: https://developers.deepgram.com/docs/tts-media-output-settings#audio-format-combinations
![image](https://github.com/twilio-labs/call-gpt/assets/116455596/30a3f802-b138-4c5c-8833-19d543956ba4)

**Comment by mercuryyy** [comment]
@SageWorks4925 Thank you for replying i usually do my research before opening a thread and actually found this today and came back here to close the thread, thank you so much for replying.
