### ISSUE TITLE
<Record> Flag on TwiML not working.

### ISSUE THREAD

**Issue by mercuryyy** [twilio-labs/call-gpt#34]
So i tried few combination from - https://www.twilio.com/docs/voice/twiml/stream

I tried having the <Record> flag set in different location while editing app.js, either errors the app, or does not record on Twilio. 

```
app.post('/incoming', (req, res) => {
  res.status(200);
  res.type('text/xml');
  res.end(`
  <Response>
    // tried here
    <Connect>
      // tried here
      <Stream url="wss://${process.env.SERVER}/connection" Record="true" />
      <Record transcribe="true" playBeep="false" />
    </Connect>
  </Response>
  `);
}); 
```

**Comment by cweems** [comment]
@mercuryyy I've incorporated call-recording functionality into the project now. The `<Record>` TwiML verb is more like "Voicemail recording" functionality that stops the rest of the call instructions while the users speaks. In this case we would update the in-progress call to start recording while the media stream is executing: https://www.twilio.com/docs/voice/api/recording

You can use this now by adding `RECORDING_ENABLED='true'` in the `.env` file. Be sure to note the legal implications of call recording listed in the `.env` file. You will also need to set your Twilio Account SID and Auth Token in the .env.
