### ISSUE TITLE
Getting this error a lot on latest code - tested -June 8 

### ISSUE THREAD

**Issue by gauravkesharwani** [twilio-labs/call-gpt#39]
After taking the latest , getting this error a lot

To help you decide, let me ask: Do you need noise cancellation in your headphones?
GPT -> user context length: 7
RangeError: Maximum call stack size exceeded
    at TextToSpeechService.generate (/Users/gauravkesharwani/Repo/call-gpt/services/tts-service.js:36:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by cweems** [comment]
@gauravkesharwani can you pull this change and see if you are able to reproduce the same error? It should be fixed now.

**Comment by gauravkesharwani** [comment]
issue is resolved now.. thank you so much!!
