### ISSUE TITLE
Error: Cannot find module '../firebase-db.json'

### ISSUE THREAD

**Issue by pBread** [twilio-labs/call-gpt#6]
There is no firebase configuration file ([it's listed in the .gitignore](https://github.com/twilio-labs/call-gpt/blob/2dd399e9d76ac5be4b33960ad26e59427a076c21/.gitignore#L147)) and no instructions on how to create said file. The app throws an error (below) when you attempt to start w/out that configuration file.

```
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '../firebase-db.json'
```

**Comment by cweems** [comment]
Hey @pBread! We decided to remove the firebase requirement for this project as it was causing some confusion on setup. This file should no longer be required.
